### ISSUE TITLE
Consider using 'Conventional Commits'.

### ISSUE THREAD

**Issue by da2ce7** [Nautilus-Cyberneering/nautilus-librarian#20]
This is a standard way of naming commits that allows us to automatically generate changelogs from our commit history.

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by josecelano** [comment]
hi @da2ce7 I've started using it: https://nautilus-cyberneering.github.io/librarian/development/#commits

You can see the latest release: https://github.com/Nautilus-Cyberneering/librarian/releases

I think it's a very god thing since we are generating releases automatically.

Do you thing we should add more information about it? I also added it to the [CONTRIBUTING.md file](https://github.com/Nautilus-Cyberneering/librarian/blob/main/CONTRIBUTING.md#committing-code-to-an-issue), but I've just realized I have to added it to the "[Commit messages](https://github.com/Nautilus-Cyberneering/librarian/blob/main/CONTRIBUTING.md#commit-messages)" section.
